import Wedding from "../assets/wedding.jpg";
import Office from "../assets/office.jpg";
import Food from "../assets/Fastfood.jpg";
import Birthday from "../assets/brithday.jpg";
import Christmas from "../assets/christmas.jpg";
import Movie from "../assets/movie.jpg";
import Cartoon from "../assets/cartoon.jpg";
import Creatures from "../assets/mythical.jpg";

export const ThingsInWedding = [
  "Bride",
  "Groom",
  "Ring",
  "Cake",
  "Dress",
  "Vows",
  "Love",
  "Kiss",
  "Champagne",
  "Guests",
  "Music",
  "Dance",
  "Family",
  "Photographer",
  "Smiles",
  "Happiness",
  "Flowers",
  "Gifts",
  "Celebration",
  "Unity",
  "Bouquet",
  "Ceremony",
  "Invitations",
  "Veil",
  "Tuxedo",
  "Rings",
  "Honeymoon",
  "Reception",
  "Toast",
  "Decorations",
  "Garter",
  "Joy",
  "Candles",
  "Commitment",
  "Harmony",
  "Tradition",
  "Memories",
  "Romance",
  "Photobook",
  "Cheers",
];

export const ThingsInOffice = [
  "Desk",
  "Computer",
  "Chair",
  "Phone",
  "Printer",
  "Files",
  "Stationery",
  "Calendar",
  "Whiteboard",
  "Coffee",
  "Laptop",
  "Notebook",
  "Pen",
  "Chair",
  "Meeting",
  "Keyboard",
  "Mouse",
  "Monitor",
  "Headphones",
  "Desk Lamp",
  "Shelves",
  "Cabinet",
  "Clock",
  "Note Pad",
  "Desk Organizer",
  "Water Bottle",
  "Plants",
  "Office Supplies",
  "Conference Room",
];

export const FoodWords = [
  "Pizza",
  "Burger",
  "Sushi",
  "Pasta",
  "Chocolate",
  "Salad",
  "Ice Cream",
  "Tacos",
  "Cheese",
  "Coffee",
  "Cupcake",
  "Smoothie",
  "Sandwich",
  "Soup",
  "Doughnut",
  "Pancakes",
  "Steak",
  "Fries",
  "Cakes",
  "Curry",
  "Popcorn",
  "Spaghetti",
  "Tiramisu",
  "Burrito",
  "Waffles",
  "Cucumber",
  "Muffin",
  "Shrimp",
  "Guacamole",
];

export const CreatureWords = [
  "Dragon",
  "Unicorn",
  "Mermaid",
  "Phoenix",
  "Yeti",
  "Griffin",
  "Sasquatch",
  "Vampire",
  "Werewolf",
  "Centaur",
  "Banshee",
  "Kraken",
  "Chimera",
  "Gargoyle",
  "Hydra",
  "Minotaur",
  "Fairy",
  "Goblin",
  "Pixie",
  "Harpy",
  "Cerberus",
  "Sphinx",
  "Ogre",
  "Kelpie",
  "Basilisk",
  "Cthulhu",
  "Elf",
  "Leviathan",
  "Leprechaun",
];

export const ThingsInBirthdayParty = [
  "Cake",
  "Balloons",
  "Gifts",
  "Candles",
  "Party Hats",
  "Decorations",
  "Streamers",
  "Confetti",
  "Games",
  "Music",
  "Invitations",
  "Tablecloth",
  "Party Favors",
  "Pinata",
  "Chocolates",
  "Birthday Banner",
  "Guests",
  "Photobooth",
  "Ice Cream",
  "Cupcakes",
  "Party Plates",
  "Beverages",
  "Party Popper",
  "Sweets",
  "Streamers",
  "DJ",
  "Dance Floor",
  "Presents",
  "Photographer",
];

export const ChristmasWords = [
  "Tree",
  "Ornaments",
  "Lights",
  "Stockings",
  "Presents",
  "Santa",
  "Sleigh",
  "Reindeer",
  "Snowflakes",
  "Snowman",
  "Candles",
  "Wreath",
  "Mistletoe",
  "Carols",
  "Cookies",
  "Gingerbread",
  "Hot Cocoa",
  "Tinsel",
  "Nutcracker",
  "Chimney",
  "Elves",
  "Jingle Bells",
  "Candy Canes",
  "Frosty",
  "Sweaters",
  "Family",
  "Joy",
  "Peace",
  "Love",
];

export const MovieTitles = [
  "Inception",
  "The Shawshank Redemption",
  "The Dark Knight",
  "Pulp Fiction",
  "Titanic",
  "Forrest Gump",
  "The Matrix",
  "The Godfather",
  "Avatar",
  "Jurassic Park",
  "The Lion King",
  "Frozen",
  "Harry Potter and the Sorcerer's Stone",
  "Star Wars: Episode IV - A New Hope",
  "The Avengers",
  "E.T. the Extra-Terrestrial",
  "Indiana Jones and the Last Crusade",
  "The Terminator",
  "The Wizard of Oz",
  "Back to the Future",
  "Casablanca",
  "Gone with the Wind",
  "The Silence of the Lambs",
  "Fight Club",
  "Braveheart",
  "Gladiator",
  "The Great Gatsby",
  "The Social Network",
  "The Shawshank Redemption",
];

export const CartoonCharacters = [
  "Mickey Mouse",
  "SpongeBob SquarePants",
  "Bugs Bunny",
  "Homer Simpson",
  "Pikachu",
  "Scooby-Doo",
  "Bart Simpson",
  "Tom and Jerry",
  "Daffy Duck",
  "Donald Duck",
  "Popeye the Sailor",
  "Dora the Explorer",
  "Snoopy",
  "Garfield",
  "Charlie Brown",
  "Spider-Man",
  "Sylvester the Cat",
  "Tweety Bird",
  "Marge Simpson",
  "Goofy",
  "Shrek",
  "Fred Flintstone",
  "Velma Dinkley",
  "Arnold (Hey Arnold!)",
  "Sailor Moon",
  "Optimus Prime",
  "Aladdin",
  "Woody",
  "Hobbes",
];

export const BeachVacationWords = [
  "Sunscreen",
  "Sandcastle",
  "Seashells",
  "Flip-flops",
  "Surfing",
  "Swimsuit",
  "Sunglasses",
  "Towel",
  "Ocean Waves",
  "Palm Trees",
  "Beach Ball",
  "Snorkeling",
  "Coconut Drink",
  "Sand Dunes",
  "Seagulls",
  "Sunset",
  "Beach Chair",
  "Hammock",
  "Picnic",
  "Frisbee",
  "Coral Reef",
  "Sailboat",
  "Ice Cream",
  "Beach Umbrella",
  "Sandbar",
  "Tropical Fish",
  "Jet Ski",
  "Shell Collecting",
  "Beach Volleyball",
];

// utils/categories.ts

export const PictionaryData = [
  {
    name: "Wedding",
    image: Wedding,
    words: ThingsInWedding,
  },
  {
    name: "Office",
    image: Office,
    words: ThingsInOffice,
  },
  {
    name: "Food",
    image: Food,
    words: FoodWords,
  },
  {
    name: "Mythical Creatures",
    image: Creatures,
    words: CreatureWords,
  },
  {
    name: "Birthday Party",
    image: Birthday,
    words: ThingsInBirthdayParty,
  },
  {
    name: "Christmas",
    image: Christmas,
    words: ChristmasWords,
  },
  {
    name: "Movie Titles",
    image: Movie,
    words: MovieTitles,
  },
  {
    name: "Cartoon Characters",
    image: Cartoon,
    words: CartoonCharacters,
  },
  // {
  //   name: "Beach Vacation",
  //   image: Beach,
  //   words: BeachVacationWords,
  // },
];
